classDiagram
  class Game_SelfSwitches {
    -_data: object

    +initialize()
    +clear()
    +value(key) boolean
    +setValue(key, value)
    +onChange()
  }
  note for Game_SelfSwitches "The game object class for self switches."
