classDiagram
  class Game_Switches {
    -_data: boolean[]

    +initialize()
    +clear()
    +value(switchId) boolean
    +setValue(switchId, value)
    +onChange()
  }
  note for Game_Switches "The game object class for switches."
