classDiagram
  class Sprite_Timer {
    -_seconds: number

    +initialize()
    +destroy(options)
    +createBitmap()
    +fontFace() string
    +fontSize() number
    +update()
    +updateBitmap()
    +redraw()
    +timerText() string
    +updatePosition()
    +updateVisibility()
  }
  note for Sprite_Timer "The sprite for displaying the timer."
