classDiagram
  class Sprite_Picture {
    -_pictureId: number
    -_pictureName: string

    +initialize(pictureId)
    +picture() any
    +update()
    +updateBitmap()
    +updateOrigin()
    +updatePosition()
    +updateScale()
    +updateTone()
    +updateOther()
    +loadBitmap()
  }
  note for Sprite_Picture "The sprite for displaying a picture."
