classDiagram
  class Sprite_Destination {
    -_frameCount: number

    +initialize()
    +destroy(options)
    +update()
    +createBitmap()
    +updatePosition()
    +updateAnimation()
  }
  note for Sprite_Destination "The sprite for displaying the destination place of the touch input."
