classDiagram
  class Window_SkillStatus {
    -_actor

    +initialize(rect)
    +setActor(actor)
    +refresh()
  }
  note for Window_SkillStatus "The window for displaying the skill user's status on the skill screen."
