classDiagram
  class Window_Selectable {
    -_index
    -_cursorFixed
    -_cursorAll
    -_helpWindow
    -_handlers
    -_doubleTouch
    -_canRepeat

    +initialize(rect)
    +index()
    +cursorFixed()
    +setCursorFixed(cursorFixed)
    +cursorAll()
    +setCursorAll(cursorAll)
    +maxCols()
    +maxItems()
    +colSpacing()
    +rowSpacing()
    +itemWidth()
    +itemHeight()
    +contentsHeight()
    +maxRows()
    +overallHeight()
    +activate()
    +deactivate()
    +select(index)
    +forceSelect(index)
    +smoothSelect(index)
    +deselect()
    +reselect()
    +row()
    +topRow()
    +maxTopRow()
    +setTopRow(row)
    +maxPageRows()
    +maxPageItems()
    +maxVisibleItems()
    +isHorizontal()
    +topIndex()
    +itemRect(index)
    +itemRectWithPadding(index)
    +itemLineRect(index)
    +setHelpWindow(helpWindow)
    +showHelpWindow()
    +hideHelpWindow()
    +setHandler(symbol, method)
    +isHandled(symbol)
    +callHandler(symbol)
    +isOpenAndActive()
    +isCursorMovable()
    +cursorDown(wrap)
    +cursorUp(wrap)
    +cursorRight(wrap)
    +cursorLeft(wrap)
    +cursorPagedown()
    +cursorPageup()
    +isScrollEnabled()
    +update()
    +processCursorMove()
    +processHandling()
    +processTouch()
    +isHoverEnabled()
    +onTouchSelect(trigger)
    +onTouchOk()
    +onTouchCancel()
    +hitIndex()
    +hitTest(x, y)
    +isTouchOkEnabled()
    +isOkEnabled()
    +isCancelEnabled()
    +isOkTriggered()
    +isCancelTriggered()
    +processOk()
    +callOkHandler()
    +processCancel()
    +callCancelHandler()
    +processPageup()
    +processPagedown()
    +updateInputData()
    +ensureCursorVisible(smooth)
    +callUpdateHelp()
    +updateHelp()
    +setHelpWindowItem(item)
    +isCurrentItemEnabled()
    +drawAllItems()
    +drawItem(index)*
    +clearItem(index)
    +drawItemBackground(index)
    +drawBackgroundRect(rect)
    +redrawItem(index)
    +redrawCurrentItem()
    +refresh()
    +paint()
    +refreshCursor()
    +refreshCursorForAll()
  }
  note for Window_Selectable "The window class with cursor movement functions."
