classDiagram
  class Window_PartyCommand {
    +initialize(rect)
    +makeCommandList()
    +setup()
  }
  note for Window_PartyCommand "The window for selecting whether to fight or escape on the battle screen."
