classDiagram
  class Window_ShopCommand {
    -_purchaseOnly

    +initialize(rect)
    +setPurchaseOnly(purchaseOnly)
    +maxCols()
    +makeCommandList()
  }
  note for Window_ShopCommand "The window for selecting buy/sell on the shop screen."
