classDiagram
  class Window_StatusParams {
    -_actor

    +initialize(rect)
    +setActor(actor)
    +maxItems()
    +itemHeight()
    +drawItem(index)
    +drawItemBackground(index)
  }
  note for Window_StatusParams "The window for displaying parameters on the status screen."
