classDiagram
  class Window_EquipCommand {
    +initialize(rect)
    +maxCols()
    +makeCommandList()
  }
  note for Window_EquipCommand "The window for selecting a command on the equipment screen."
