classDiagram
  class Window_BattleLog {
    -_lines
    -_methods
    -_waitCount
    -_waitMode
    -_baseLineStack
    -_spriteset

    +initialize(rect)
    +setSpriteset(spriteset)
    +maxLines()
    +numLines()
    +messageSpeed()
    +isBusy()
    +update()
    +updateWait()
    +updateWaitCount()
    +updateWaitMode()
    +setWaitMode(waitMode)
    +callNextMethod()
    +isFastForward()
    +push(methodName)
    +clear()
    +wait()
    +waitForEffect()
    +waitForMovement()
    +addText(text)
    +pushBaseLine()
    +popBaseLine()
    +waitForNewLine()
    +popupDamage(target)
    +performActionStart(subject, action)
    +performAction(subject, action)
    +performActionEnd(subject)
    +performDamage(target)
    +performMiss(target)
    +performRecovery(target)
    +performEvasion(target)
    +performMagicEvasion(target)
    +performCounter(target)
    +performReflection(target)
    +performSubstitute(substitute, target)
    +performCollapse(target)
    +showAnimation(subject, targets, animationId)
    +showAttackAnimation(subject, targets)
    +showActorAttackAnimation(subject, targets)
    +showEnemyAttackAnimation()
    +showNormalAnimation(targets, animationId, mirror)
    +refresh()
    +drawBackground()
    +backRect()
    +lineRect(index)
    +backColor()
    +backPaintOpacity()
    +drawLineText(index)
    +startTurn()
    +startAction(subject, action, targets)
    +endAction(subject)
    +displayCurrentState(subject)
    +displayRegeneration(subject)
    +displayAction(subject, item)
    +displayItemMessage(fmt, subject, item)
    +displayCounter(target)
    +displayReflection(target)
    +displaySubstitute(substitute, target)
    +displayActionResults(subject, target)
    +displayFailure(target)
    +displayCritical(target)
    +displayDamage(target)
    +displayMiss(target)
    +displayEvasion(target)
    +displayHpDamage(target)
    +displayMpDamage(target)
    +displayTpDamage(target)
    +displayAffectedStatus(target)
    +displayAutoAffectedStatus(target)
    +displayChangedStates(target)
    +displayAddedStates(target)
    +displayRemovedStates(target)
    +displayChangedBuffs(target)
    +displayBuffs(target, buffs, fmt)
    +makeHpDamageText(target)
    +makeMpDamageText(target)
    +makeTpDamageText(target)
  }
  note for Window_BattleLog "The window for displaying battle progress. No frame is displayed, but it is handled as a window for convenience."
