classDiagram
  class Window_Gold {
    +initialize(rect)
    +colSpacing()
    +refresh()
    +value()
    +currencyUnit()
    +open()
  }
  note for Window_Gold "The window for displaying the party's gold."
