classDiagram
  class Window_StatusBase {
    -_additionalSprites

    +initialize(rect)
    +loadFaceImages()
    +refresh()
    +hideAdditionalSprites()
    +placeActorName(actor, x, y)
    +placeStateIcon(actor, x, y)
    +placeGauge(actor, type, x, y)
    +createInnerSprite(key, spriteClass)
    +placeTimeGauge(actor, x, y)
    +placeBasicGauges(actor, x, y)
    +gaugeLineHeight()
    +drawActorCharacter(actor, x, y)
    +drawActorFace(actor, x, y, width, height)
    +drawActorName(actor, x, y, width)
    +drawActorClass(actor, x, y, width)
    +drawActorNickname(actor, x, y, width)
    +drawActorLevel(actor, x, y)
    +drawActorIcons(actor, x, y, width)
    +drawActorSimpleStatus(actor, x, y)
    +actorSlotName(actor, index)
  }
  note for Window_StatusBase "The superclass of windows for displaying actor status."
