classDiagram
  class Window_Help {
    -_text

    +initialize(rect)
    +setText(text)
    +clear()
    +setItem(item)
    +refresh()
  }
  note for Window_Help "The window for displaying the description of the selected item."
