classDiagram
  class Window_Base {
    -_opening
    -_closing
    -_dimmerSprite

    +initialize(rect)
    +destroy(options)
    +checkRectObject(rect)
    +lineHeight()
    +itemWidth()
    +itemHeight()
    +itemPadding()
    +baseTextRect()
    +loadWindowskin()
    +updatePadding()
    +updateBackOpacity()
    +fittingHeight(numLines)
    +updateTone()
    +createContents()
    +destroyContents()
    +contentsWidth()
    +contentsHeight()
    +resetFontSettings()
    +resetTextColor()
    +update()
    +updateOpen()
    +updateClose()
    +open()
    +close()
    +isOpening()
    +isClosing()
    +show()
    +hide()
    +activate()
    +deactivate()
    +systemColor()
    +translucentOpacity()
    +changeTextColor(color)
    +changeOutlineColor(color)
    +changePaintOpacity(enabled)
    +drawRect(x, y, width, height)
    +drawText(text, x, y, maxWidth, align)
    +textWidth(text)
    +drawTextEx(text, x, y, width)
    +textSizeEx(text)
    +createTextState(text, x, y, width)
    +processAllText(textState)
    +flushTextState(textState)
    +createTextBuffer(rtl)
    +convertEscapeCharacters(text)
    +actorName(n)
    +partyMemberName(n)
    +processCharacter(textState)
    +processControlCharacter(textState, c)
    +processNewLine(textState)
    +obtainEscapeCode(textState)
    +obtainEscapeParam(textState)
    +processEscapeCharacter(code, textState)
    +processColorChange(colorIndex)
    +processDrawIcon(iconIndex, textState)
    +makeFontBigger()
    +makeFontSmaller()
    +calcTextHeight(textState)
    +maxFontSizeInLine(line)
    +drawIcon(iconIndex, x, y)
    +drawFace(faceName, faceIndex, x, y, width, height)
    +drawCharacter(characterName, characterIndex, x, y)
    +drawItemName(item, x, y, width)
    +drawCurrencyValue(value, unit, x, y, width)
    +setBackgroundType(type)
    +showBackgroundDimmer()
    +createDimmerSprite()
    +hideBackgroundDimmer()
    +updateBackgroundDimmer()
    +refreshDimmerBitmap()
    +playCursorSound()
    +playOkSound()
    +playBuzzerSound()
  }
  note for Window_Base "The superclass of all windows within the game."
