classDiagram
  class Window_NameBox {
    -_name
    -_messageWindow

    +initialize()
    +setMessageWindow(messageWindow)
    +setName(name)
    +clear()
    +start()
    +updatePlacement()
    +updateBackground()
    +windowWidth()
    +windowHeight()
    +refresh()
  }
  note for Window_NameBox "The window for displaying a speaker name above the message window."
