classDiagram
  class Window_MapName {
    -_showCount

    +initialize(rect)
    +update()
    +updateFadeIn()
    +updateFadeOut()
    +open()
    +close()
    +refresh()
    +drawBackground(x, y, width, height)
  }
  note for Window_MapName "The window for displaying the map name on the map screen."
