classDiagram
  class Window_MenuActor {
    +initialize(rect)
    +processOk()
    +selectLast()
    +selectForItem(item)
  }
  note for Window_MenuActor "The window for selecting a target actor on the item and skill screens."
