classDiagram
  class Window_StatusEquip {
    -_actor

    +initialize(rect)
    +setActor(actor)
    +maxItems()
    +itemHeight()
    +drawItem(index)
    +drawItemBackground(index)
  }
  note for Window_StatusEquip "The window for displaying equipment items on the status screen."
