classDiagram
  class DataManager
  class ConfigManager
  class StorageManager
  class FontManager
  class ImageManager
  class EffectManager
  class AudioManager
  class SoundManager
  class TextManager
  class ColorManager
  class SceneManager
  class BattleManager
  class PluginManager
