classDiagram
  class SoundManager {
    +preloadImportantSounds()
    +loadSystemSound(n)
    +playSystemSound(n)
    +playCursor()
    +playOk()
    +playCancel()
    +playBuzzer()
    +playEquip()
    +playSave()
    +playLoad()
    +playBattleStart()
    +playEscape()
    +playEnemyAttack()
    +playEnemyDamage()
    +playEnemyCollapse()
    +playBossCollapse1()
    +playBossCollapse2()
    +playActorDamage()
    +playActorCollapse()
    +playRecovery()
    +playMiss()
    +playEvasion()
    +playMagicEvasion()
    +playReflection()
    +playShop()
    +playUseItem()
    +playUseSkill()
  }
  note for SoundManager "The static class that plays sound effects defined in the database."
