classDiagram
  class Scene_Gameover {
    -_backSprite: Sprite

    +initialize()
    +create()
    +start()
    +update()
    +stop()
    +terminate()
    +playGameoverMusic()
    +createBackground()
    +adjustBackground()
    +isTriggered() boolean
    +gotoTitle()
  }
  note for Scene_Gameover "The scene class of the game over screen."
